### ISSUE TITLE
Compile errors after Arduino IDE and libraries update

### ISSUE THREAD

**Issue by Sebastix** [lnbits/nostr-zap-lamp#27]
I've updated Arduino IDE from `2.3.2` to `2.3.3` and the installed libraries:

![](https://shares.sebastix.dev/CPAcEB9z.png#2d99f223a645ae48b08c6eefcb2c4d67fc13cc5e0d847a895f3738527cda6879)

Now when I try to verify/compile the .ino file:

```sh
In file included from /home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:11,
                 from /home/sebastian/Arduino/libraries/Nostr/src/NostrEvent.h:15,
                 from /home/sebastian/Desktop/Nostr Zap Lamp/nostr-zap-lamp/nostrZapLamp/nostrZapLamp.ino:23:
/home/sebastian/Arduino/libraries/uBitcoin/src/Networks.h:42:3: error: 'typedef struct Network Network' redeclared as different kind of entity
   42 | } Network;
      |   ^~~~~~~
In file included from /home/sebastian/.arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/Network/src/Network.h:10,
                 from /home/sebastian/.arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/WiFi/src/WiFiGeneric.h:39,
                 from /home/sebastian/.arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/WiFi/src/WiFiSTA.h:29,
                 from /home/sebastian/.arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/WiFi/src/WiFi.h:33,
                 from /home/sebastian/Desktop/Nostr Zap Lamp/nostr-zap-lamp/nostrZapLamp/nostrZapLamp.ino:21:
/home/sebastian/.arduino15/packages/esp32/hardware/esp32/3.0.5/libraries/Network/src/NetworkManager.h:34:23: note: previous declaration 'NetworkManager Network'
   34 | extern NetworkManager Network;
      |                       ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Networks.h:44:14: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
   44 | extern const Network Mainnet;
      |              ^~~~~~~
      |              NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Networks.h:45:14: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
   45 | extern const Network Testnet;
      |              ^~~~~~~
      |              NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Networks.h:46:14: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
   46 | extern const Network Regtest;
      |              ^~~~~~~
      |              NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Networks.h:47:14: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
   47 | extern const Network Signet;
      |              ^~~~~~~
      |              NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Networks.h:49:14: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
   49 | extern const Network * networks[];
      |              ^~~~~~~
      |              NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:117:54: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  117 |     int legacyAddress(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                      ^~~~~~~
      |                                                      NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:121:54: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  121 |     int segwitAddress(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                      ^~~~~~~
      |                                                      NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:125:60: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  125 |     int nestedSegwitAddress(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                            ^~~~~~~
      |                                                            NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:129:51: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  129 |     int address(char * address, size_t len, const Network * network = &DEFAULT_NETWORK) const{ return legacyAddress(address, len, network); };
      |                                                   ^~~~~~~
      |                                                   NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:131:32: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  131 |     String legacyAddress(const Network * network = &DEFAULT_NETWORK) const;
      |                                ^~~~~~~
      |                                NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:132:32: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  132 |     String segwitAddress(const Network * network = &DEFAULT_NETWORK) const;
      |                                ^~~~~~~
      |                                NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:133:38: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  133 |     String nestedSegwitAddress(const Network * network = &DEFAULT_NETWORK) const;
      |                                      ^~~~~~~
      |                                      NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:134:26: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  134 |     String address(const Network * network = &DEFAULT_NETWORK) const{ return legacyAddress(network); };
      |                          ^~~~~~~
      |                          NetworkUDP
In file included from /home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:7:
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:117:75: note: in expansion of macro 'DEFAULT_NETWORK'
  117 |     int legacyAddress(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                                           ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:121:75: note: in expansion of macro 'DEFAULT_NETWORK'
  121 |     int segwitAddress(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                                           ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:125:81: note: in expansion of macro 'DEFAULT_NETWORK'
  125 |     int nestedSegwitAddress(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                                                 ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:129:72: note: in expansion of macro 'DEFAULT_NETWORK'
  129 |     int address(char * address, size_t len, const Network * network = &DEFAULT_NETWORK) const{ return legacyAddress(address, len, network); };
      |                                                                        ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:131:53: note: in expansion of macro 'DEFAULT_NETWORK'
  131 |     String legacyAddress(const Network * network = &DEFAULT_NETWORK) const;
      |                                                     ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:132:53: note: in expansion of macro 'DEFAULT_NETWORK'
  132 |     String segwitAddress(const Network * network = &DEFAULT_NETWORK) const;
      |                                                     ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:133:59: note: in expansion of macro 'DEFAULT_NETWORK'
  133 |     String nestedSegwitAddress(const Network * network = &DEFAULT_NETWORK) const;
      |                                                           ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:134:47: note: in expansion of macro 'DEFAULT_NETWORK'
  134 |     String address(const Network * network = &DEFAULT_NETWORK) const{ return legacyAddress(network); };
      |                                               ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:170:80: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  170 |     PrivateKey(const uint8_t secret_arr[32], bool use_compressed = true, const Network * net = &DEFAULT_NETWORK);
      |                                                                                ^~~~~~~
      |                                                                                NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:186:11: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  186 |     const Network * network;
      |           ^~~~~~~
      |           NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:170:97: note: in expansion of macro 'DEFAULT_NETWORK'
  170 |     PrivateKey(const uint8_t secret_arr[32], bool use_compressed = true, const Network * net = &DEFAULT_NETWORK);
      |                                                                                                 ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:258:24: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  258 |                  const Network * network = &DEFAULT_NETWORK,
      |                        ^~~~~~~
      |                        NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:261:112: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  261 |     HDPrivateKey(const char * mnemonic, size_t mnemonicSize, const char * password, size_t passwordSize, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                                                                                ^~~~~~~
      |                                                                                                                NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:266:58: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  266 |     HDPrivateKey(String mnemonic, String password, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                          ^~~~~~~
      |                                                          NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:283:63: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  283 |     int fromSeed(const uint8_t * seed, size_t seedSize, const Network * network = &DEFAULT_NETWORK);
      |                                                               ^~~~~~~
      |                                                               NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:285:116: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  285 |     int fromMnemonic(const char * mnemonic, size_t mnemonicSize, const char * password, size_t passwordSize, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                                                                                    ^~~~~~~
      |                                                                                                                    NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:286:74: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  286 |     int fromMnemonic(const char * mnemonic, const char * password, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL){
      |                                                                          ^~~~~~~
      |                                                                          NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:293:62: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  293 |     int fromMnemonic(String mnemonic, String password, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                              ^~~~~~~
      |                                                              NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:258:45: note: in expansion of macro 'DEFAULT_NETWORK'
  258 |                  const Network * network = &DEFAULT_NETWORK,
      |                                             ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:261:133: note: in expansion of macro 'DEFAULT_NETWORK'
  261 |     HDPrivateKey(const char * mnemonic, size_t mnemonicSize, const char * password, size_t passwordSize, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                                                                                                     ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:266:79: note: in expansion of macro 'DEFAULT_NETWORK'
  266 |     HDPrivateKey(String mnemonic, String password, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                                               ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:283:84: note: in expansion of macro 'DEFAULT_NETWORK'
  283 |     int fromSeed(const uint8_t * seed, size_t seedSize, const Network * network = &DEFAULT_NETWORK);
      |                                                                                    ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:285:137: note: in expansion of macro 'DEFAULT_NETWORK'
  285 |     int fromMnemonic(const char * mnemonic, size_t mnemonicSize, const char * password, size_t passwordSize, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                                                                                                         ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:286:95: note: in expansion of macro 'DEFAULT_NETWORK'
  286 |     int fromMnemonic(const char * mnemonic, const char * password, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL){
      |                                                                                               ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:293:83: note: in expansion of macro 'DEFAULT_NETWORK'
  293 |     int fromMnemonic(String mnemonic, String password, const Network * network = &DEFAULT_NETWORK, void (*progress_callback)(float) = NULL);
      |                                                                                   ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:352:24: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  352 |                  const Network * net = &DEFAULT_NETWORK,
      |                        ^~~~~~~
      |                        NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:373:11: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  373 |     const Network * network;
      |           ^~~~~~~
      |           NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:352:41: note: in expansion of macro 'DEFAULT_NETWORK'
  352 |                  const Network * net = &DEFAULT_NETWORK,
      |                                         ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:508:53: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  508 |     size_t address(char * buffer, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                     ^~~~~~~
      |                                                     NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:510:26: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  510 |     String address(const Network * network = &DEFAULT_NETWORK) const;
      |                          ^~~~~~~
      |                          NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:508:74: note: in expansion of macro 'DEFAULT_NETWORK'
  508 |     size_t address(char * buffer, size_t len, const Network * network = &DEFAULT_NETWORK) const;
      |                                                                          ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:510:47: note: in expansion of macro 'DEFAULT_NETWORK'
  510 |     String address(const Network * network = &DEFAULT_NETWORK) const;
      |                                               ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:645:51: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  645 |     size_t address(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const{ return scriptPubkey.address(addr, len, network); };
      |                                                   ^~~~~~~
      |                                                   NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:647:26: error: 'Network' does not name a type; did you mean 'NetworkUDP'?
  647 |     String address(const Network * network = &DEFAULT_NETWORK) const{ return scriptPubkey.address(network); };
      |                          ^~~~~~~
      |                          NetworkUDP
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:645:72: note: in expansion of macro 'DEFAULT_NETWORK'
  645 |     size_t address(char * addr, size_t len, const Network * network = &DEFAULT_NETWORK) const{ return scriptPubkey.address(addr, len, network); };
      |                                                                        ^~~~~~~~~~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/uBitcoin_conf.h:5:25: error: 'Mainnet' was not declared in this scope
    5 | #define DEFAULT_NETWORK Mainnet
      |                         ^~~~~~~
/home/sebastian/Arduino/libraries/uBitcoin/src/Bitcoin.h:647:47: note: in expansion of macro 'DEFAULT_NETWORK'
  647 |     String address(const Network * network = &DEFAULT_NETWORK) const{ return scriptPubkey.address(network); };
      |                                               ^~~~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1
```

I guess a library is causing this, but I don't know why. Can I set the version of a specific library back so I can try to get things back to work on specific versions?

**Comment by blackcoffeexbt** [comment]
Odd. Did it compile with 2.3.2?

Do you have vs code with platformio extension installed? Can you try building using that if so?

**Comment by Sebastix** [comment]
I'm using the Arduino IDE and don't have any VScode based IDE installed.
I just tried version 2.3.2 and also replaced the updates libraries which older versions. But the same errors keep popping up. I think it's something related to my OS (laptop with Linux Mint),

I tried another compile on my MacOS device with Arduino 2.3.2 where I didn't do any updates since I was building the zaplamp (back in May this year) and there everything works as expected.

These are the current packages / libraries which could be updated:
- esp32 v2.0.11 by espressif systems 
- arduinojson v7.0.4
- websockets v2.4.0

**Comment by Sebastix** [comment]
The issue is related to the esp32 package provided by Espressif Systems.
When using version 3.0.x it breaks. With version 2.0.x everything works.

**Comment by Sebastix** [comment]
See https://github.com/nostrver-se/nostr-zap-lamp/commit/eb4fc9f08bc0b9fef5c6470fd9dd68ff89c2a2ed

**Comment by dni** [comment]
hey, i fixed it here: https://github.com/lnbits/nostr-zap-lamp/pull/28
